#! /bin/sh

xrandr -s 1360x768
xmodmap ~/.xmodmap
sxhkd &
$HOME/.config/bspwm/panel/panel &

#每个屏幕工作区分配
bspc monitor -d I II III IV V 
bspc monitor LVDS1 -d 1 2 3 4 5
bspc monitor VGA1 -d 6 7 8 9 0
# bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor DVI-I-1 -d I II III IV
# bspc monitor DVI-I-2 -d V VI VII
# bspc monitor DP-1 -d VIII IX X

# bspc config border_width         2
# bspc config window_gap          12
bspc config border_width         1
bspc config window_gap          1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
