[theme]
name = "native"

[theme.overrides]
idle_fg = "#ffffff"
warning_bg = "#de5833"
warning_fg = "#ffffff"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"
[block.theme_overrides]
idle_bg = "#00223f"
idle_fg = "#ffffff"

[[block]]
block = "net"
device = "enp0s31f6"
format = "{ssid} {signal_strength} {speed_up;K*b} {speed_down;K*b}"
interval = 5

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}"
chip = "*-isa-*"
interval = 5
warning = 55

[[block]]
block = "cpu"
interval = 2
format = "{utilization}"
warning = 38
critical = 60

[[block]]
block = "memory"
format_mem = "{mem_avail}/{mem_total}"
format_swap = "{swap_used}/{swap_total}"
display_type = "memory"
clickable = true
interval = 5
warning_mem = 78
critical_mem = 88

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
unit = "GB"
interval = 45

[[block]]
block = "load"
format = "{1m}"
interval = 3
info = 4.5
warning = 6
critical = 8.5

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "sound"
format = "{output_description} {volume}"

[[block]]
block = "time"
format = "%a %d/%m %R"
interval = 60
