[theme.overrides]
separator = " "
idle_fg = "#ffffff"
warning_fg = "#de5833"

[[block]]
block = "focused_window"
max_width = 100
show_marks = "visible"
[block.theme_overrides]
idle_bg = "#00223f"
idle_fg = "#ffffff"

[[block]]
block = "net"
device = "enp0s31f6"
device = "wlp2s0"
format = "↓ {speed_down;K*b} ↑ {speed_up;K*b}  - {ip} - {signal_strength} - {ssid}"
icons_format = ""
interval = 1

[[block]]
block = "temperature"
collapsed = false
interval = 1
format = "{average}{max}"
icons_format = ""
chip = "*-isa-*"
warning = 58
[block.theme_overrides]
info_fg = "#FCFF3D"

[[block]]
block = "cpu"
interval = 5
format = "{utilization}"
icons_format = ""
warning = 38
critical = 60

[[block]]
block = "memory"
format_mem = "{mem_avail}/{mem_total}"
format_swap = "{swap_used}/{swap_total}"
display_type = "memory"
icons_format = ""
clickable = true
interval = 10
warning_mem = 78
critical_mem = 88

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
unit = "GB"
interval = 45

[[block]]
block = "load"
format = "{1m} {5m} {15m}"
icons_format = ""
interval = 5
info = 4.5
warning = 6
critical = 8.5

[[block]]
block = "backlight"
icons_format = "*"
device = "intel_backlight"

[[block]]
block = "sound"
icons_format = ""
format = "{output_description} {volume}"
on_click = "swaymsg exec 'pavucontrol'"

[[block]]
block = "battery"
interval = 30
driver = "sysfs"
format = "{percentage} {time}"

[[block]]
block = "time"
icons_format = ""
format = "%a %d/%m %R"
interval = 60
on_click = "systemctl `echo -e 'suspend\npoweroff\nreboot' | dmenu`"
