#!/bin/sh
#xfreerdp /v:bdpc60 /d:bd /u:mmohler /p:Uhi83883@ /monitors:2,1 /multimon -compression /rfx +clipboard
if [ "$1" = "dualRight" ]; then
  # xrandr --output eDP --auto --left-of DisplayPort-4 --output DisplayPort-4 --auto --left-of DisplayPort-2 --output DisplayPort-2 --auto
    xrandr --output HDMI-1 --auto --left-of eDP-1
fi
if [ "$1" = "HDMI" ]; then
  # xrandr --output LVDS1 --off --output DP1 --auto
    xrandr --output eDP-1 --off --output HDMI-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal 
fi
if [ "$1" = "laptop" ]; then
  # xrandr --output eDP --auto --output DisplayPort-4 --off --output DisplayPort-2 --off
    xrandr --output HDMI1 --off --output VIRTUAL1 --off --output eDP-1 --primary --mode 1360x768--pos 0x0 --rotate normal
fi
#xrandr --output LVDS1 --auto --right-of DP1 --output DP1 --mode 1920x1080 
# ~/.fehbg
